# renew_before_expiry = 30 days
version = 3.1.0
archive_dir = /home/mmoerz/src/Ordi3/certbot/archive/ordimoerz.at
cert = /home/mmoerz/src/Ordi3/certbot/live/ordimoerz.at/cert.pem
privkey = /home/mmoerz/src/Ordi3/certbot/live/ordimoerz.at/privkey.pem
chain = /home/mmoerz/src/Ordi3/certbot/live/ordimoerz.at/chain.pem
fullchain = /home/mmoerz/src/Ordi3/certbot/live/ordimoerz.at/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 07b142782235b6ac0db56bebac1b4652
rsa_key_size = 4096
pref_challs = http-01, dns-01
config_dir = /home/mmoerz/src/Ordi3/certbot
work_dir = /home/mmoerz/src/Ordi3/certbot/work
logs_dir = /home/mmoerz/src/Ordi3/certbot/log
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = manual
key_type = ecdsa
